version: '3.1'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: them
      POSTGRES_USER: me
      POSTGRES_DB: uptick
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres-data-uptick:/var/lib/postgresql/data